apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: hello-world-param-    #name of workflow spec
spec:
  entrypoint: whalesay          #invoke the whalesay template
  arguments:
    parameters:
      - name: message
        value: hello world

  templates:
  - name: whalesay              #name of template
    inputs:
      parameters:
        - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
      resources:                #don't use too much resources
        limits:
          memory: 32Mi
          cpu: 100m

