apiVersion: v1
kind: Pod

metadata:
  name: xgboost
  labels:
    team: dcoe

spec:
  containers:
  - name: xgboost
    image: azcore.azurecr.io/dev/ames-housing:v1
    volumeMounts:
    - mountPath: "/mnt/xgboost"
      name: volume
    args:
      - --train-input
      - /mnt/xgboost/ames_dataset/train.csv
      - --model-file
      - /mnt/xgboost/housing.dat
      - --learning-rate
      - "0.1"
      - --n-estimators
      - "30000"
      - --early-stopping-rounds
      - "50"
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: azurefile

